use crate::ast::{DataType, Ident};

#[derive(Debug, Clone, Copy)]
pub enum SQL {
    MSAccess,
    LibreOfficeBase,
    MySQL,
    PostgreSQL,
    MSSQL,
}

impl SQL {
    pub fn from_str(s: &str) -> Option<Self> {
        match s {
            "ms_access" => Some(Self::MSAccess),
            "libre_office_base" => Some(Self::LibreOfficeBase),
            "mysql" => Some(Self::MySQL),
            "postgresql" => Some(Self::PostgreSQL),
            "mssql" => Some(Self::MSSQL),
            _ => None,
        }
    }
}

// The methods needed for SQL creation
impl SQL {
    pub fn to_data_type(&self, data_type: &DataType) -> String {
        match self {
            Self::MSAccess => ms_access::to_data_type(data_type),
            Self::LibreOfficeBase => libre_office_base::to_data_type(data_type),
            Self::MySQL => mysql::to_data_type(data_type),
            Self::PostgreSQL => postgresql::to_data_type(data_type),
            Self::MSSQL => mssql::to_data_type(data_type),
        }
    }

    pub fn to_column_ident(&self, ident: &Ident) -> String {
        match self {
            Self::MSAccess => ms_access::to_column_ident(ident),
            Self::LibreOfficeBase => libre_office_base::to_column_ident(ident),
            Self::MySQL => mysql::to_column_ident(ident),
            Self::PostgreSQL => postgresql::to_column_ident(ident),
            Self::MSSQL => mssql::to_column_ident(ident),
        }
    }
}

mod ms_access {
    use crate::ast::{DataType, Ident};

    pub fn to_data_type(data_type: &DataType) -> String {
        match data_type {
            DataType::Integer => "INTEGER".to_string(),
            DataType::AutoIncrement => "AUTOINCREMENT".to_string(),
            DataType::Float => "FLOAT".to_string(),
            DataType::Boolean => "YESNO".to_string(),
            DataType::Date => "DATE".to_string(),
            DataType::Time => "TIME".to_string(),
            DataType::DateTime => "DATETIME".to_string(),
            DataType::Varchar(n) => format!("VARCHAR({})", n),
        }
    }
    pub fn to_column_ident(ident: &Ident) -> String {
        format!("[{}]", ident.to_string())
    }
}

mod libre_office_base {
    use crate::ast::{DataType, Ident};

    // See http://www.hsqldb.org/doc/1.8/guide/guide.html#datatypes-section
    pub fn to_data_type(data_type: &DataType) -> String {
        match data_type {
            DataType::Integer => "INTEGER".to_string(),
            DataType::AutoIncrement => "INTEGER GENERATED BY DEFAULT AS IDENTITY".to_string(),
            DataType::Float => "FLOAT".to_string(),
            DataType::Boolean => "BOOLEAN".to_string(),
            DataType::Date => "DATE".to_string(),
            DataType::Time => "TIME".to_string(),
            DataType::DateTime => "DATETIME".to_string(),
            DataType::Varchar(n) => format!("VARCHAR({})", n),
        }
    }
    pub fn to_column_ident(ident: &Ident) -> String {
        ident.to_string()
    }
}

mod mysql {
    use crate::ast::{DataType, Ident};

    pub fn to_data_type(data_type: &DataType) -> String {
        match data_type {
            DataType::Integer => "INTEGER".to_string(),
            DataType::AutoIncrement => "INTEGER AUTO_INCREMENT".to_string(),
            DataType::Float => "FLOAT".to_string(),
            DataType::Boolean => "BOOLEAN".to_string(),
            DataType::Date => "DATE".to_string(),
            DataType::Time => "TIME".to_string(),
            DataType::DateTime => "DATETIME".to_string(),
            DataType::Varchar(n) => format!("VARCHAR({})", n),
        }
    }
    pub fn to_column_ident(ident: &Ident) -> String {
        ident.to_string()
    }
}

mod postgresql {
    use crate::ast::{DataType, Ident};

    pub fn to_data_type(data_type: &DataType) -> String {
        match data_type {
            DataType::Integer => "INTEGER".to_string(),
            DataType::AutoIncrement => "SERIAL".to_string(),
            DataType::Float => "FLOAT".to_string(),
            DataType::Boolean => "BOOLEAN".to_string(),
            DataType::Date => "DATE".to_string(),
            DataType::Time => "TIME".to_string(),
            DataType::DateTime => "DATETIME".to_string(),
            DataType::Varchar(n) => format!("VARCHAR({})", n),
        }
    }
    pub fn to_column_ident(ident: &Ident) -> String {
        ident.to_string()
    }
}

mod mssql {
    use crate::ast::{DataType, Ident};

    pub fn to_data_type(data_type: &DataType) -> String {
        match data_type {
            DataType::Integer => "INTEGER".to_string(),
            DataType::AutoIncrement => "INTEGER IDENTITY(1,1)".to_string(),
            DataType::Float => "FLOAT".to_string(),
            DataType::Boolean => "BOOLEAN".to_string(),
            DataType::Date => "DATE".to_string(),
            DataType::Time => "TIME".to_string(),
            DataType::DateTime => "DATETIME".to_string(),
            DataType::Varchar(n) => format!("VARCHAR({})", n),
        }
    }
    pub fn to_column_ident(ident: &Ident) -> String {
        ident.to_string()
    }
}
